name: rdt_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.11.7
- pytorch=2.6.0
- numpy=1.26.3
- pandas=2.2.2
- matplotlib=3.8.2
- seaborn=0.13.2
- scikit-learn=1.4.0
- pyyaml=6.0.1
- biopython=1.83
- tqdm=4.66.1
- typing_extensions=4.9.0
- mafft=7.525